DESCRIPTION, R/item_get_parent.R
=> Fix for error catch (dup of item_get)

DESCRIPTION, R/item_replace_files.R
=> fix for error in item_replace_files()

DESCRIPTION, R/REST_helpers.R
@lawinslow - this OK with you?
=> 1-line change to permit download of tsv files

DESCRIPTION
Do change the `Description` field as needed, just put something in there to start.
=> DESCRIPTION file updates, fix #92

R/item_get.R, R/item_get_fields.R, R/item_get_parent.R, R/item_list_files.R, R/item_upload_create.R, R/query_items.R, inst/examples/books.json, man/item_get.Rd, man/item_get_fields.Rd, man/item_get_parent.Rd, man/item_list_files.Rd, man/item_upload_create.Rd, man/query_items.Rd
=> Added egs to many functions

DESCRIPTION, R/item_rm.R
This modification, for some reason, allows us to remove an item even if it has attached items.
=> fixed item remove issue #41

R/REST_helpers.R, R/item_rm.R, tests/testthat/test-REST.R
fix #80 
Let me know if you want any changes in this PR
=> REST helpers improvments

tests/testthat/test-REST.R, tests/testthat/test-eg.R, tests/testthat/test-expiration.R
fix #85
get it? cookie....monster ?
=> remove use of cookie param in httr::handle call

R/user_id.R, man/user_id.Rd
=> check whether authed or not in user_id

.travis.yml
so multiple versions of R can be tested at once. Addresses issue #101
=> Try switching metacran builder

DESCRIPTION, R/REST_helpers.R
@ldecicco-USGS could you give this a whirl?
=> Fixed issue with item_file_download and PDF

manuscript/winslow-introduction.tex, manuscript/winslow-sbtoolsapi.tex, manuscript/winslow.bib, manuscript/winslow.tex
- changes to four sections of the manuscript
- i put comments on specific commits on github instead of including in my changes
- i changed a few pkg calls to cite calls and included references for those
- did a number of grammar fixes
=> scott's MS edits

manuscript/winslow-introduction.tex, manuscript/winslow-sbtoolsapi.tex, manuscript/winslow-sciencebase.tex, manuscript/winslow-summary.tex, manuscript/winslow.tex
@lawinslow looks good. Here are some edits
=> Jordan's edits

DESCRIPTION, manuscript/winslow-sbtoolsapi.tex, manuscript/winslow-sciencebase.tex, manuscript/winslow-summary.tex
Incorporated final BAO feedback. I also added "acknowledgments" section. Does anyone @jread-usgs @aappling-usgs @sckott want to add anything? If not, I'll submit the final version back to the journal.
=> Final edits to Manuscript

DESCRIPTION, R/current_session.R, R/identifier_exists.R, R/item_get.R, R/item_get_fields.R, R/query_sb_spatial.R, R/sb_ping.R, man/current_session.Rd, man/identifier_exists.Rd, man/item_get.Rd, man/item_get_fields.Rd, man/query_sb_spatial.Rd, man/sb_ping.Rd, manuscript/RJwrapper.tex, manuscript/winslow-chamberlain-appling-read.tex, manuscript/winslow-sbtoolsapi.tex, manuscript/winslow-sciencebase.tex, manuscript/winslow.bib
feedback from CRAN maintainers and R Journal
=> Manuscript and package changes

.latex.yml, README.md, manuscript/winslow-sbtoolsapi.tex
remove pdf builder links
manuscript copyedit changes
=> Some package cleanup

DESCRIPTION, R/sbtools-package.R, inst/CITATION, man/sbtools-package.Rd
=> Add manuscript citation info

README.md
@ldecicco-USGS, @lawinslow  - how's this?
=> manuscript link & more extensive examples in README

DESCRIPTION
I must have forgotten to merge this.
=> Merge in my latest fork

manuscript/winslow.bib
Same as https://github.com/USGS-R/dataRetrieval/pull/444 ;-)
=> Hyperlink DOIs against preferred resolver

DESCRIPTION, R/item_get.R, R/item_get_parent.R, R/sb_item.R, man/folder_create.Rd, man/item_list_files.Rd, man/item_rename_files.Rd, man/query_sb_datatype.Rd, man/query_sb_date.Rd
[sbtools_1.1.8.tar.gz](https://github.com/USGS-R/sbtools/files/3952291/sbtools_1.1.8.tar.gz)
Fixes #250 tar.gz is attached to be uploaded to cran. 🤞 that does the trick.
=> switch to donttest so CRAN checks don't fail when SB is down.

DESCRIPTION, R/REST_helpers.R, R/item_get_fields.R, R/item_list_children.R, R/item_list_files.R, R/set_endpoint.R, man/folder_create.Rd, man/item_create.Rd, man/item_file_download.Rd, man/item_get_fields.Rd, man/item_list_children.Rd, man/item_list_files.Rd, man/item_rename_files.Rd, man/item_replace_files.Rd, man/item_rm.Rd, man/item_update_identifier.Rd, man/item_upsert.Rd, man/items_create.Rd, man/items_upsert.Rd, man/query_item_identifier.Rd, man/query_item_in_folder.Rd, man/query_sb_datatype.Rd, man/query_sb_date.Rd, man/query_sb_spatial.Rd, man/set_endpoint.Rd
This is on it's way to CRAN to take care of some CRAN check issues that produced #257
=> fixes #257
